

export const storeProducts = [
  {
    id: 1,
    title: "Colourful Room",
    img: "img/colorfullamp.jpg",
    info:"If your want to have amazing expreince using PhilipsHue? Do not miss your chance to use this service",
    inCart: false,
    inProgress:false,
    failConnecting:false,
    services:[],
    requiredServices:[],
    serviceId:[],
    urls:[],
    mes:[],
  },
  {
    id: 2,
    title: "Resting Environment",
    img: "img/resting.jpg",
    info:"Service is intended to provide comfortable lighting to give your rest.",
    inCart: false,
    inProgress:false,
    failConnecting:false,
    services:[],
    requiredServices:[],
    serviceId:[],
    urls:[],
    mes:[],
    code:[],
  },
  {
    id: 3,
    title: "Studying",
    img: "img/studying.jpg",
    info:"This service provides birghtness to your studying environment to get A+ from your exams.",
    inCart: false,
    inProgress:false,
    failConnecting:false,
    services:[],
    requiredServices:[],
    serviceId:[],
    urls:[],
    mes:[],
    code:[],
  },
];

export const detailProduct =  {
  id: 1,
  title: "Colourful Room",
  img: "img/colorfullamp.jpg",
  info:
    "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  inProgress:false,
  failConnecting:false,
  services:[],
  requiredServices:[],
  serviceId:[],
  urls:[],
  mes:[],
  code:[],
};